# ===============================
# = HTTP/HTTPS
# ===============================
server:
  port: 8082
  servlet:
    context-path: /tjpupc

# ===============================
# = SPRING CONFIG
# ===============================
spring:
  profiles:
    active: prod
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: utf-8
  redis:
    # 连接超时时间
    timeout: 5000ms
    # Redis数据库索引（默认为0
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池中的最大空闲连接
        max-idle: 18
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# ===============================
# = MYBATIS
# ===============================
mybatis:
  typeAliasesPackage: cn.tjpuacm.contest_regsiter_service.*.*.po
  mapperLocations: classpath:mapper/**/*Mapper.xml
  configuration:
    default-statement-timeout: 20
